In [1]:
import pandas as pd

In [6]:
df=pd.read_csv("C:/Users/Tcs/Desktop/eee86/ppml_emp.csv")
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [7]:
df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [8]:
df.head(2)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB

In [10]:
df.to_string()

'      First Name  Gender  Start Date Last Login Time  Salary  Bonus % Senior Management                  Team\n0        Douglas    Male    8/6/1993        12:42 PM   97308    6.945              True             Marketing\n1         Thomas    Male   3/31/1996         6:53 AM   61933    4.170              True                   NaN\n2          Maria  Female   4/23/1993        11:17 AM  130590   11.858             False               Finance\n3          Jerry    Male    3/4/2005         1:00 PM  138705    9.340              True               Finance\n4          Larry    Male   1/24/1998         4:47 PM  101004    1.389              True       Client Services\n5         Dennis    Male   4/18/1987         1:35 AM  115163   10.125             False                 Legal\n6           Ruby  Female   8/17/1987         4:20 PM   65476   10.012              True               Product\n7            NaN  Female   7/20/2015        10:43 AM   45906   11.598               NaN               Finance\n8         Angela  Female  11/22/2005         6:29 AM   95570   18.523              True           Engineering\n9        Frances  Female    8/8/2002         6:51 AM  139852    7.524              True  Business Development\n10        Louise  Female   8/12/1980         9:01 AM   63241   15.132              True                   NaN\n11         Julie  Female  10/26/1997         3:19 PM  102508   12.637              True                 Legal\n12       Brandon    Male   12/1/1980         1:08 AM  112807   17.492              True       Human Resources\n13          Gary    Male   1/27/2008        11:40 PM  109831    5.831             False                 Sales\n14      Kimberly  Female   1/14/1999         7:13 AM   41426   14.543              True               Finance\n15       Lillian  Female    6/5/2016         6:09 AM   59414    1.256             False               Product\n16        Jeremy    Male   9/21/2010         5:56 AM   90370    7.369             False       Human Resources\n17         Shawn    Male   12/7/1986         7:45 PM  111737    6.414             False               Product\n18         Diana  Female  10/23/1981        10:27 AM  132940   19.082             False       Client Services\n19         Donna  Female   7/22/2010         3:48 AM   81014    1.894             False               Product\n20          Lois     NaN   4/22/1995         7:18 PM   64714    4.934              True                 Legal\n21       Matthew    Male    9/5/1995         2:12 AM  100612   13.645             False             Marketing\n22        Joshua     NaN    3/8/2012         1:58 AM   90816   18.816              True       Client Services\n23           NaN    Male   6/14/2012         4:19 PM  125792    5.042               NaN                   NaN\n24          John    Male    7/1/1992        10:08 PM   97950   13.873             False       Client Services\n25           NaN    Male   10/8/2012         1:12 AM   37076   18.576               NaN       Client Services\n26         Craig    Male   2/27/2000         7:45 AM   37598    7.757              True             Marketing\n27         Scott     NaN   7/11/1991         6:58 PM  122367    5.218             False                 Legal\n28         Terry    Male  11/27/1981         6:30 PM  124008   13.464              True       Client Services\n29      Benjamin    Male   1/26/2005        10:06 PM   79529    7.008              True                 Legal\n30     Christina  Female    8/6/2002         1:19 PM  118780    9.096              True           Engineering\n31         Joyce     NaN   2/20/2005         2:40 PM   88657   12.752             False               Product\n32           NaN    Male   8/21/1998         2:27 PM  122340    6.417               NaN                   NaN\n33          Jean  Female  12/18/1993         9:07 AM  119082   16.180             False  Business Development\n34         Jerry    Male   1/10/2004        12:56 PM   95734   19.096             False       Client Services\n35       Theresa  Female  10/10/2006         1:12 AM   85182   16.675             False                 Sales\n36        Rachel  Female   2/16/2009         8:47 PM  142032   12.599             False  Business Development\n37         Linda  Female  10/19/1981         8:49 PM   57427    9.557              True       Client Services\n38     Stephanie  Female   9/13/1986         1:52 AM   36844    5.574              True  Business Development\n39           NaN    Male   1/29/2016         2:33 AM  122173    7.797               NaN       Client Services\n40       Michael    Male  10/10/2008        11:25 AM   99283    2.665              True          Distribution\n41     Christine     NaN   6/28/2015         1:08 AM   66582   11.308              True  Business Development\n42       Beverly  Female    9/9/1998         8:26 PM  121918   15.835             False                 Legal\n43       Marilyn  Female   12/7/1980         3:16 AM   73524    5.207              True             Marketing\n44       Cynthia  Female  11/16/1988         6:54 PM  145146    7.482              True               Product\n45         Roger    Male   4/17/1980        11:32 AM   88010   13.886              True                 Sales\n46         Bruce    Male  11/28/2009        10:47 PM  114796    6.796             False               Finance\n47         Kathy  Female   6/22/2005         4:51 AM   66820    9.000              True       Client Services\n48      Clarence    Male   3/26/1996         5:57 AM   93581    6.083              True  Business Development\n49         Chris     NaN   1/24/1980        12:13 PM  113590    3.055             False                 Sales\n50         Nancy  Female   9/23/2000         8:05 AM   94976   13.830              True           Engineering\n51           NaN     NaN  12/17/2011         8:29 AM   41126   14.009               NaN                 Sales\n52          Todd    Male   2/18/1990         2:41 AM   49339    1.695              True       Human Resources\n53          Alan     NaN    3/3/2014         1:28 PM   40341   17.578              True               Finance\n54          Sara  Female   8/15/2007         9:23 AM   83677    8.999             False           Engineering\n55         Karen  Female  11/30/1999         7:46 AM  102488   17.653              True               Product\n56          Carl    Male    5/3/2006         5:55 PM  130276   16.084              True               Finance\n57         Henry    Male   6/26/1996         1:44 AM   64715   15.107              True       Human Resources\n58       Theresa  Female   4/11/2010         7:18 AM   72670    1.481              True           Engineering\n59         Irene  Female    5/7/1997         9:32 AM   66851   11.279             False           Engineering\n60         Paula     NaN  11/23/2005         2:01 PM   48866    4.271             False          Distribution\n61        Denise  Female   11/6/2001        12:03 PM  106862    3.699             False  Business Development\n62           NaN  Female   6/12/2007         5:25 PM   58112   19.414               NaN             Marketing\n63       Matthew    Male    1/2/2013        10:33 PM   35203   18.040             False       Human Resources\n64      Kathleen     NaN   4/11/1990         6:46 PM   77834   18.771             False  Business Development\n65         Steve    Male  11/11/2009        11:44 PM   61310   12.428              True          Distribution\n66         Nancy  Female  12/15/2012        11:57 PM  125250    2.672              True  Business Development\n67        Rachel  Female   8/16/1999         6:53 AM   51178    9.735              True               Finance\n68          Jose    Male  10/30/2004         1:39 PM   84834   14.330              True               Finance\n69         Irene     NaN   7/14/2015         4:31 PM  100863    4.382              True               Finance\n70          Todd     NaN   6/10/2003         2:26 PM   84692    6.617             False       Client Services\n71        Johnny    Male   11/6/2009         4:23 PM  118172   16.194              True                 Sales\n72         Bobby    Male    5/7/2007        10:01 AM   54043    3.833             False               Product\n73       Frances  Female    4/4/1999         4:19 PM   90582    4.709              True                 Sales\n74        Thomas    Male    6/4/1995         2:24 PM   62096   17.029             False             Marketing\n75        Bonnie  Female    7/2/1991         1:27 AM  104897    5.118              True       Human Resources\n76      Margaret  Female   9/10/1988        12:42 PM  131604    7.353              True          Distribution\n77       Charles    Male   9/14/2004         8:13 PM  107391    1.260              True             Marketing\n78         Robin  Female    6/4/1983         3:15 PM  114797    5.965              True                 Sales\n79        Bonnie  Female  11/13/1988         3:30 PM  115814    4.990             False               Product\n80        Gerald     NaN   3/17/1995        12:50 AM  137126   15.602              True                 Sales\n81   Christopher    Male   3/30/2008        10:52 AM   47369   14.822             False                 Legal\n82        Steven    Male   3/30/1980         9:20 PM   35095    8.379              True       Client Services\n83         Shawn    Male   9/23/2005         2:55 AM  148115    6.539              True               Finance\n84         Doris  Female   8/20/2004         5:51 AM   83072    7.511             False               Finance\n85        Jeremy    Male    2/1/2008         8:50 AM  100238    3.887              True       Client Services\n86         Annie     NaN   9/29/2007        12:11 AM  103495   17.290              True  Business Development\n87         Annie  Female   1/30/1993         2:05 AM  144887    8.276              True                 Sales\n88         Donna  Female  11/27/1991         1:59 PM   64088    6.155              True                 Legal\n89        Janice  Female   3/12/2016        12:40 AM   51082   11.955             False                 Legal\n90        Janice     NaN   8/21/1997         5:12 AM   91719   11.583              True                 Legal\n91         James     NaN   1/26/2005        11:00 PM  128771    8.309             False                   NaN\n92         Linda  Female   5/25/2000         5:45 PM  119009   12.506              True  Business Development\n93      Virginia     NaN    5/7/1994         5:58 PM  111858    1.601              True                 Legal\n94         Harry    Male   8/26/1981         3:16 PM  130620    7.030             False                 Legal\n95       Heather  Female   7/11/1998         2:17 PM   43026   14.166             False       Client Services\n96       Cynthia  Female   3/21/1994         8:34 AM  142321    1.737             False               Finance\n97         Laura     NaN   7/19/2014         9:23 PM  140371   10.620              True             Marketing\n98          Tina  Female   6/16/2016         7:47 PM  100705   16.961              True             Marketing\n99        Harold    Male    1/2/1985         9:40 PM   77544   12.447             False  Business Development\n100      Melissa  Female   6/21/2005         6:33 AM   48109   14.995             False               Finance\n101        Aaron    Male   2/17/2012        10:20 AM   61602   11.849              True             Marketing\n102         Jack    Male   1/12/1997         5:51 AM  103902   12.159             False       Client Services\n103      Phyllis  Female  10/11/1996         9:30 PM  136984    8.932              True               Finance\n104         John    Male  12/23/1989         7:01 AM   80740   19.305             False             Marketing\n105        Kathy  Female    3/9/1996         4:33 AM   91712    8.567             False               Finance\n106         Paul    Male    8/4/1993         7:25 PM   42146    3.046             False                 Legal\n107       Steven    Male   4/23/2013        10:12 PM   68680   16.565             False                 Legal\n108      Russell     NaN    5/5/1988         7:57 AM  133980   12.396              True                 Legal\n109  Christopher    Male   4/22/2000        10:15 AM   37919   11.449             False                   NaN\n110      Shirley  Female   6/20/2001        10:39 PM  147113   16.135             False                 Legal\n111       Bonnie  Female  12/17/1999         3:12 PM   42153    8.454              True  Business Development\n112       Willie    Male  11/27/2003         6:21 AM   64363    4.023             False             Marketing\n113         Tina  Female   6/12/2009         7:16 AM  114767    3.711              True           Engineering\n114       Ashley  Female    8/4/2002        11:00 AM   58698    6.811              True  Business Development\n115       Pamela  Female    7/1/1982         6:51 AM   54585    4.166             False               Product\n116          NaN    Male   6/22/1991         8:58 PM   76189   18.988               NaN                 Legal\n117       Steven    Male    3/1/1995         3:03 PM  109095    9.494             False               Finance\n118       Andrea  Female   1/12/2012         5:43 AM  120204    9.557             False  Business Development\n119         Paul    Male    6/3/2008         3:05 PM   41054   12.299             False             Marketing\n120        Peter    Male  11/17/1994         6:15 PM   84885   15.402             False  Business Development\n121     Kathleen     NaN    5/9/2016         8:55 AM  119735   18.740             False               Product\n122    Christina  Female   4/13/2012         2:04 PM  110169   13.892              True           Engineering\n123        Helen  Female  11/29/2001         2:30 AM   73789   14.841              True               Product\n124      Marilyn  Female  11/16/1983         8:29 AM   76078    2.401              True               Product\n125     Patricia  Female    9/1/2003         6:46 AM   49368   14.226             False       Human Resources\n126     Michelle  Female   3/30/1984         6:43 PM   57325   17.179              True       Human Resources\n127      William    Male   9/29/2002         4:09 PM   66521    5.830             False       Human Resources\n128      Kenneth    Male   8/25/1987         9:16 PM  127654   16.439              True       Client Services\n129      Antonio    Male  10/25/1988         1:50 PM   60866   13.101              True  Business Development\n130      Shirley  Female    5/1/1984         1:15 PM   41334    6.219              True       Human Resources\n131      Rebecca  Female   7/10/1992        12:23 AM   94231   17.517             False               Product\n132       Carlos    Male    1/4/1995         7:02 AM  146670   10.763             False       Human Resources\n133         Lois  Female  12/25/1987         4:16 PM  106317    2.235              True       Client Services\n134      Carolyn  Female    4/9/2011         5:38 AM  109260    2.650              True  Business Development\n135       Gloria  Female   6/29/2007         5:34 AM  134148    8.833              True                 Legal\n136        Henry    Male   4/24/1995         4:18 AM   43542   19.687             False                 Legal\n137         Adam    Male   5/21/2011         1:45 AM   95327   15.120             False          Distribution\n138       Ashley  Female   5/25/2006        11:30 AM  112238    6.030              True           Engineering\n139          NaN  Female   10/3/1990         1:08 AM  132373   10.527               NaN                   NaN\n140      Shirley  Female   2/28/1981         1:23 PM  113850    1.854             False             Marketing\n141         Adam    Male  12/24/1990         8:57 PM  110194   14.727              True               Product\n142    Elizabeth  Female   10/9/2003         5:53 PM  146129    5.687             False               Finance\n143       Teresa     NaN   1/28/2016        10:55 AM  140013    8.689              True           Engineering\n144       Nicole     NaN    3/5/1982         2:28 PM  122717   12.452             False                 Sales\n145     Jennifer  Female    4/4/2009        10:47 PM   71715   13.079              True       Client Services\n146     Patricia  Female  11/25/1992         2:24 AM   95322    4.150             False               Product\n147       Philip    Male   7/17/2008         1:30 PM   89227    3.996             False                 Legal\n148      Patrick     NaN   7/14/1991         2:24 AM  124488   14.837              True                 Sales\n149          NaN  Female   8/17/2014         2:00 PM   86230    8.578               NaN          Distribution\n150         Sean    Male    5/4/1996         8:59 PM  135490   19.934             False             Marketing\n151      Brandon     NaN   11/3/1997         8:17 PM  121333   15.295             False  Business Development\n152         Ruth  Female   8/19/1999         4:03 AM  129297    8.067              True       Client Services\n153       Victor     NaN   3/10/2011         8:40 PM   84546   10.489              True               Finance\n154      Rebecca  Female  11/15/1980         4:13 AM   85730    5.359              True               Product\n155        Marie  Female   3/16/2003        12:12 AM  104058   17.695              True  Business Development\n156       Howard    Male   4/27/1992         1:10 AM  105062    1.563             False       Human Resources\n157          NaN  Female   7/27/2005         8:32 AM   79536   14.443               NaN               Product\n158        Norma  Female   2/28/1999         8:45 PM  114412    8.756              True             Marketing\n159        James     NaN  11/22/1983        10:52 PM   68501   14.316             False             Marketing\n160        Kathy  Female   3/18/2000         7:26 PM  149563   16.991              True               Finance\n161      Marilyn     NaN   8/22/1999         9:09 AM  103386   11.451             False          Distribution\n162       Arthur    Male   4/13/1998        11:28 AM   89786   14.422              True                 Legal\n163        Terry    Male    9/3/1990         9:15 PM   52226   19.135             False       Client Services\n164         Mary  Female   8/13/1999         1:03 AM  134645   18.197             False  Business Development\n165          NaN  Female   3/23/2014         1:28 PM   59148    9.061               NaN                 Legal\n166          NaN  Female    7/9/1991         6:52 PM   42341    7.014               NaN                 Sales\n167  Christopher    Male  12/24/2011        12:22 PM  142178   17.984              True                 Sales\n168        Peter     NaN    9/3/1987         5:59 PM   38989    7.017              True             Marketing\n169     Michelle  Female   11/4/1996         9:34 PM   53754    5.455              True               Product\n170        Irene  Female   1/29/1992        11:36 AM  133772   19.020              True                 Sales\n171      Patrick    Male   8/17/2007         3:16 AM  143499   17.495              True           Engineering\n172         Sara  Female   9/23/1991         6:17 PM   97058    9.402             False               Finance\n173      Lillian  Female  12/21/2008         6:51 PM   85446    3.959              True           Engineering\n174          NaN     NaN   9/18/2007         6:59 PM   40297    6.185               NaN       Client Services\n175       Willie    Male   2/17/1998         8:20 PM  146651    1.451              True           Engineering\n176       Victor    Male    1/8/2003         1:02 PM  124486   10.166             False               Product\n177        Wayne    Male    4/7/2012         8:00 AM  102652   14.085              True          Distribution\n178         Jane  Female    9/3/1997         2:01 AM  144474   17.648             False               Product\n179      Jessica  F

In [15]:
df1.columns

Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
       'Bonus %', 'Senior Management', 'Team'],
      dtype='object')

In [16]:
df.shape

(1000, 8)

In [19]:
df['Team']

0                 Marketing
1                       NaN
2                   Finance
3                   Finance
4           Client Services
               ...
995            Distribution
996                 Finance
997                 Product
998    Business Development
999                   Sales
Name: Team, Length: 1000, dtype: object

In [20]:
df[2:10:2]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
6,Ruby,Female,8/17/1987,4:20 PM,65476,10.012,True,Product
8,Angela,Female,11/22/2005,6:29 AM,95570,18.523,True,Engineering

In [21]:
df.loc[86]

First Name                          Annie
Gender                                NaN
Start Date                      9/29/2007
Last Login Time                  12:11 AM
Salary                             103495
Bonus %                             17.29
Senior Management                    True
Team                 Business Development
Name: 86, dtype: object

In [28]:
df.loc[df['Gender']=='Male']

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
5,Dennis,Male,4/18/1987,1:35 AM,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [30]:
dff=df['Salary']/30
print(dff)

0      3243.600000
1      2064.433333
2      4353.000000
3      4623.500000
4      3366.800000
          ...
995    4416.100000
996    1413.066667
997    3230.466667
998    2016.666667
999    4331.633333
Name: Salary, Length: 1000, dtype: float64